-- MySQL Setup Commands
-- Generated by run_mysql_setup.R

CREATE DATABASE IF NOT EXISTS fraud_detection_db;
USE fraud_detection_db;

CREATE TABLE IF NOT EXISTS transactions (
    transaction_id INT PRIMARY KEY AUTO_INCREMENT,
    customer_id INT,
    transaction_date DATETIME,
    fraud_probability DECIMAL(5,4),
    fraud_prediction INT,
    actual_label INT,
    amount DECIMAL(10,2),
    INDEX idx_customer (customer_id),
    INDEX idx_date (transaction_date)
);

